// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isaletrrbohmkimljrzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzYWxldHJyYm9obWtpbWxqcnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTUyODUsImV4cCI6MjA2ODEzMTI4NX0.MIyICnsz8nEj5oyDxhu1-j7qdF9LIcvcYzZvea0kVkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});